### ISSUE TITLE
Assignment1 code review

### ISSUE THREAD

**Issue by blackboxlogic** [GGPotato/Cos470#4]
Please include the output (file and console) of assignment1 for a dramatic increase in grade.

We usually commit the entire solution/project/code so that it can be used with minimal setup.

Lots of commented out code which is just clutter.

Regarding:
https://github.com/GGPotato/Cos470/blob/f90f05d8331a2b54727a6a64aaadb80c9aa1148b/Assignment1#L110-L225
This can be simplified significantly.

**Comment by blackboxlogic** [comment]
I'm a little confused what I'm looking at. There is a zip file in your code? There are two similar code files with the `Assignment1._1` namespace but only one is has the .cs file ext? I don't think 'abettal' is the most expensive word.

**Comment by GGPotato** [comment]
Yeah, my bad, abettal is only worth $0.61, and as for the files, I will
send them again I was unsure what I needed to send in so I just sent
everything.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by blackboxlogic** [comment]
When I click those links I get an advertisement for virus protection.
